name: Builder

on:
  workflow_dispatch:
  push:
    branches: ["master"]

jobs:

  windows-vs2019:
    runs-on: windows-2019

    env:
      GCP_PKG_NAME: GoogleChromePortable_128.0.6613.120_online.paf.exe
      CHROME_PKG_NAME: 49.0.2623.75_chrome64_stable_windows_installer.exe
      PRODUCT_NAME: Chrome_49.0.2623.75

    steps:
      # 检出代码
      - uses: actions/checkout@v3

      # 下载GoogleChromePortable
      - name: download GoogleChromePortable
        if: steps.cache-GoogleChromePortable.outputs.cache-hit != 'true'
        run: |
          mkdir GoogleChromePortable
          cd GoogleChromePortable
          Invoke-WebRequest -Uri https://download2.portableapps.com/portableapps/GoogleChromePortable/${{ env.GCP_PKG_NAME }} -OutFile ${{ env.GCP_PKG_NAME }}
          7z x ${{ env.GCP_PKG_NAME }} -aoa
      
      # 缓存GoogleChromePortable
      - name: cache-GoogleChromePortable
        id: cache-GoogleChromePortable
        uses: actions/cache@v1
        with:
          path: "GoogleChromePortable/${{ env.GCP_PKG_NAME }}"
          key: ${{ env.GCP_PKG_NAME }}

      # 提取Chrome
      - name: extract chrome
        run: |
          7z x ${{ env.CHROME_PKG_NAME }} -aoa
          7z x chrome.7z -aoa

      # 使用7z压缩
      - name: 7zip
        run: |
          mkdir ${{ env.PRODUCT_NAME }}
          cp GoogleChromePortable/GoogleChromePortable.exe ${{ env.PRODUCT_NAME }}/
          mkdir ${{ env.PRODUCT_NAME }}/App
          cp -r Chrome-bin ${{ env.PRODUCT_NAME }}/App
          del archive.7z
          del archive.exe
          7z a archive.7z ${{ env.PRODUCT_NAME }} -mx0
          copy /b ".\7zip\7z.sfx" + ".\7zip\config.txt" + archive.7z ${{ env.PRODUCT_NAME }}.exe

      # 上传artifact
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PRODUCT_NAME }}
          path: ${{ env.PRODUCT_NAME }}.exe